import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/global.scss";
import ReduxProvider from "@/redux/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "auto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
